services:
  db:
    image: postgres:16
    container_name: postgres_latest
    restart: always
    environment:
      POSTGRES_USER: pulseuser
      POSTGRES_PASSWORD: pulsepassword
      POSTGRES_DB: pulsedatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulseuser -d pulsedatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  postgres_data:
